### ISSUE TITLE
Default "split-thread-core-pool-size" to 4

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-task-app-starters/composed-task-runner#40]
See spring-cloud/spring-cloud-dataflow#2279 for more details.

**Comment by cppwfs** [comment]
We had a discussion at inception of CTR because, I had defaulted it to 5 (IIRC) when we working on the initial release. It was decided to stay at 1 because :
1) it was a sensible default.
2) It prevents users from reporting the issue as a scaling problem, i.e. "I ran 6 and now it fails for some odd reason".  And I will repeat the question I was asked when I defaulted to 5.  Why 5?  in this case why 4?

**Comment by sabbyanandan** [comment]
@mminella: Do you have any recommendations?

**Comment by cppwfs** [comment]
Let's discuss.    But the original reason for using 1 was not to choose an arbitrary number of threads.   By selecting the default of 1 users could tune it to their needs.   We can set it to 4, but we will see this issue reported again when the users have 5 concurrent splits.
